
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: egeriaservers.egeria.egeria-project.org
spec:
  group: egeria.egeria-project.org
  names:
    kind: EgeriaServer
    listKind: EgeriaServerList
    plural: egeriaservers
    singular: egeriaserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EgeriaServer is the Schema for the egeriaservers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Desired state for Egeria Server
            properties:
              config:
                description: Reference to location of server config document (exact
                  details not yet known)
                type: string
              name:
                description: server name (as known by Egeria)
                type: string
              replicas:
                description: number of replicas
                format: int32
                type: integer
            required:
            - config
            - name
            - replicas
            type: object
          status:
            description: Observed state of Egeria Server
            properties:
              platformname:
                description: Name of the platform (flavour) we are running on
                type: string
              status:
                description: current status - unknown, inactive, active
                type: string
            required:
            - platformname
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
